services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: todoapp
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongodb_data:
