pipeline{
    agent any
    stages { 
        stage("Running docker compose"){ 
            steps{ 
                script { 
                    sh "docker compose -f To-Do-list/docker-compose.yml up -d" 
                }
            }
        }
    }
}
