services: 
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports: 
     - "3000:3000"
    

  backend:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  mongo:
    image: mongo:4.4
    ports: 
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


volumes:
  mongo-data:
